openapi: "3.0.3"
info:
  title: "dp_oppdrag API"
  description: "dp_oppdrag API"
  version: "1.0.0"
servers:
- url: "https://dp_oppdrag"
paths:
  /:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello, world!"