version: '3.7'
services:
  db:
    image: "postgres:14-alpine"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "dp-oppdrag-user"
      POSTGRES_PASSWORD: "dp-oppdrag-password"
      POSTGRES_DB: "dp-oppdrag"
  mq:
    container_name: ibmmq_container
    image: ibmcom/mq:latest
    restart: always
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: passw0rd
    ports:
      - "1414:1414"
      - "9443:9443"
