oppdrag.mq:
  queuemanager: ${MQ_QUEUEMANAGER}
  send: ${MQ_OPPDRAG_QUEUE}
  mottak: ${MQ_KVITTERING_QUEUE}
  avstemming: ${MQ_AVSTEMMING_QUEUE}
  tss: QA.Q1_415.AS10_SAMHANDLER_SERVICE
  channel: ${MQ_CHANNEL}}
  hostname: ${MQ_HOSTNAME}
  port: ${MQ_PORT}
  user: ${MQ_USER}
  password: ${SERVICEUSER_PASSWORD}
  enabled: ${MQ_ENABLED}

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    cookie_name: azure_token

OPPDRAG_SERVICE_URL: ${OPPDRAG_SERVICE_URL}
SECURITYTOKENSERVICE_URL: ${STS_URL}
TILBAKEKREVING_V1_URL: https://cics.adeo.no/oppdrag/K231CW80