name: DP-Oppdrag-Simulering Build-Deploy
on:
  push:
    paths:
      - 'dp-oppdrag-simulering/**'
      - '.nais/simulering-**'
      - 'pom.xml'
      - '.github/workflows/build-and-deploy-simulering.yml'
    branches-ignore:
      - 'dependabot/**'

env:
  IMAGE: ghcr.io/navikt/dp-oppdrag-simulering:${{ github.sha }}
jobs:
  build:
    name: Bygg app/image, push til github
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --no-transfer-progress package verify --settings .m2/maven-settings.xml --file dp-oppdrag-simulering/pom.xml

      - name: Bygg Docker image
        run: |
          docker build -t $IMAGE ./dp-oppdrag-simulering

      - name: Login to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin

      - name: Push Docker image med versjonstag
        run: docker push ${IMAGE}

  deploy-dev:
    name: Deploy to dev-fss
    needs: build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: nais/deploy/actions/deploy@v2
          env:
            APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
            CLUSTER: dev-fss
            RESOURCE: .nais/simulering-nais.yaml
            VARS: .nais/simulering-vars-dev.yaml

#  deploy-prod:
#    name: Deploy to prod-fss
#    needs: deploy-dev
#    if: github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: nais/deploy/actions/deploy@v2
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-fss
#          RESOURCE: .nais/simulering-nais.yaml
#          VARS: .nais/simulering-vars-prod.yaml
