name: DP-oppdrag Build-Deploy
on:
  push:
    paths:
      - 'dp-oppdrag-app/**'
      - 'dp-oppdrag-felles/**'
      - '.nais/oppdrag-**'
      - 'pom.xml'
      - '.github/workflows/build-and-deploy-oppdrag.yml'
    branches-ignore:
      - 'dependabot/**'

env:
  IMAGE: ghcr.io/navikt/dp-oppdrag:${{ github.sha }}
jobs:
  build:
    name: Bygg app/image, push til github
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --no-transfer-progress package verify --settings .m2/maven-settings.xml --file pom.xml

      - name: Bygg Docker image
        run: |
          docker build -t $IMAGE ./dp-oppdrag-app

      - name: Login to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin

      - name: Push Docker image med versjonstag
        run: docker push ${IMAGE}

  deploy-dev:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: nais/deploy/actions/deploy@v2
          env:
            APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
            CLUSTER: dev-gcp
            RESOURCE: .nais/oppdrag-nais.yaml
            VARS: .nais/oppdrag-vars-dev.yaml

  deploy-prod:
    name: Deploy to prod-gcp
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/oppdrag-nais.yaml
          VARS: .nais/oppdrag-vars-prod.yaml
